In [1]:
!pip install pandas
!pip install numpy
!pip install matplotlib

Requirement already satisfied: pandas in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.24.2)
Requirement already satisfied: six>=1.5 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (1.24.2)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (3.8.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.42.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy<2,>=1.21 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.24.2)
Requirement already satisfied: packaging>=20.0 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=8 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (10.0.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (1.24.2)
Requirement already satisfied: pandas>=1.2 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (1.5.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (3.8.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.42.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.1)
Requirement already satisfied: pillow>=8 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.0.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\muhammad raihan\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
#Import Library yang dibutuhkan
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
dataset = pd.read_csv("C:\\Data Raihan\\Data Analyst Portofolio\\1 Tech Company Funding\\Tech Company Funding\\tech_fundings.csv") #Import Dataset

In [6]:
# Cek Tipe Data
dataset.dtypes

index                    int64
Company                 object
Website                 object
Region                  object
Vertical                object
Funding Amount (USD)    object
Funding Stage           object
Funding Date            object
dtype: object

In [8]:
# Cek Null atau nilai data yang kosong
dataset.isnull().sum()

index                    0
Company                  0
Website                  0
Region                  12
Vertical                 0
Funding Amount (USD)     0
Funding Stage            0
Funding Date             0
dtype: int64

In [9]:
# Menampilkan 10 data terakhir
dataset.tail(10)

,index,Company,Website,Region,Vertical,Funding Amount (USD),Funding Stage,Funding Date
3565,3566,Volta Trucks,https://voltatrucks.com/,Sweden,Transportation,43334400,Series B,Sep-21
3566,3567,WestConnex,https://www.westconnex.com.au/,Australia,Transportation,16600000000,Private Equity,Sep-21
3567,3568,BluSmart Mobility,https://www.blu-smart.com/,India,Transportation,24896631,Series A,Sep-21
3568,3569,StreetDrone,https://www.streetdrone.com,United Kingdom,Transportation,4113750,Series A,Sep-21
3569,3570,SmarterTravel,https://www.smartertravel.com/,United States,Travel,9500000,Series B,Sep-21
3570,3571,Headout,https://www.headout.com,United States,Travel,12000000,Series B,Sep-21
3571,3572,OLIO,https://olioex.com/,United Kingdom,Wellness,43000000,Series B,Sep-21
3572,3573,Trees for Life,https://treesforlife.org.uk,United Kingdom,Wellness,2737468,Crowdfunding,Sep-21
3573,3574,Britishvolt,https://britishvolt.com/,United Kingdom,Wellness,70000000,Series B,Sep-21
3574,3575,Greenly,https://www.greenly.earth/,France,Wellness,2953675,Seed,Sep-21

In [10]:
# Menghapus kolom index karena tidak digunakan
dataset.drop(columns=['index'], inplace=True)

In [12]:
# Menghapus kolom Website karena tidak digunakan (ada null juga)
dataset.drop(columns=['Website'], inplace=True)

In [13]:
# Menampilkan 20 data teratas pada dataset
dataset.head(20)

,Company,Region,Vertical,Funding Amount (USD),Funding Stage,Funding Date
0,Internxt,Spain,Blockchain,278940,Seed,Jan-20
1,Dockflow,Belgium,Logistics,292244,Seed,Jan-20
2,api.video,France,Developer APIs,300000,Seed,Jan-20
3,Buck.ai,United States,Artificial Intelligence,300000,Seed,Jan-20
4,Prodsight,United Kingdom,Artificial Intelligence,529013,Seed,Jan-20
5,Harvestr,France,B2B Software,650000,Angel,Jan-20
6,Seatrec,United States,Marine Technology,970000,Seed,Jan-20
7,BeeCanvas,United States,B2B Software,1000000,Seed,Jan-20
8,SmartKarrot,United States,B2B Software,1000000,Angel,Jan-20
9,Prisync,Turkey,B2B Software,1100000,Seed,Jan-20
10,Fundraise Up,United States,B2B Software,1250000,Seed,Jan-20
11,Yac,United States,B2B Software,1250000,Seed,Jan-20
12,Cloverleaf.me,United States,Human Resources,1300000,Seed,Jan-20
13,Docket,United States,B2B Software,1500000,Seed,Jan-20
14,Podsights,United States,Marketing,1500000,Seed,Jan-20
15,SIMBA Chain,United States,Blockchain,1500000,Seed,Jan-20
16,HeyTeam,France,B2B Software,1544561,Series A,Jan-20
17,Float,United Kingdom,B2B Software,1955982,Seed,Jan-20
18,Banxa,Australia,Blockchain,2000000,Series A,Jan-20
19,Defendify,United States,Cyber Security,2000000,Seed,Jan-20

In [14]:
# Melakukan Filter data untuk perusahaan yang diberikan pendanaan di negara United States saja
dataset2 = dataset.query("Region == 'United States'")

# Menampilkan 20 data teratas pada dataset 2 (Sudah di filter)
dataset2.head(20)

,Company,Region,Vertical,Funding Amount (USD),Funding Stage,Funding Date
3,Buck.ai,United States,Artificial Intelligence,300000,Seed,Jan-20
6,Seatrec,United States,Marine Technology,970000,Seed,Jan-20
7,BeeCanvas,United States,B2B Software,1000000,Seed,Jan-20
8,SmartKarrot,United States,B2B Software,1000000,Angel,Jan-20
10,Fundraise Up,United States,B2B Software,1250000,Seed,Jan-20
11,Yac,United States,B2B Software,1250000,Seed,Jan-20
12,Cloverleaf.me,United States,Human Resources,1300000,Seed,Jan-20
13,Docket,United States,B2B Software,1500000,Seed,Jan-20
14,Podsights,United States,Marketing,1500000,Seed,Jan-20
15,SIMBA Chain,United States,Blockchain,1500000,Seed,Jan-20
19,Defendify,United States,Cyber Security,2000000,Seed,Jan-20
21,OpenPhone,United States,B2B Software,2000000,Seed,Jan-20
22,Punch List,United States,Home Renovation,2000000,Seed,Jan-20
30,Kloud.io,United States,B2B Software,4000000,Seed,Jan-20
32,Upflex,United States,CoWorking,4100000,Seed,Jan-20
34,1Huddle,United States,Human Resources,5000000,Series A,Jan-20
37,Luxury Presence,United States,Real Estate,5400000,Series A,Jan-20
39,Lynq,United States,Hardware,6000000,Seed,Jan-20
40,Stoplight,United States,B2B Software,6000000,Series A,Jan-20
43,TypingDNA,United States,Artificial Intelligence,7000000,Series A,Jan-20

In [15]:
# Mengubah dataframe dataset2 menjadi .CSV
dataset2.to_csv('Company Funding US.csv', index=False)
dataset2 = pd.read_csv('Company Funding US.csv')
dataset2

,Company,Region,Vertical,Funding Amount (USD),Funding Stage,Funding Date
0,Buck.ai,United States,Artificial Intelligence,300000,Seed,Jan-20
1,Seatrec,United States,Marine Technology,970000,Seed,Jan-20
2,BeeCanvas,United States,B2B Software,1000000,Seed,Jan-20
3,SmartKarrot,United States,B2B Software,1000000,Angel,Jan-20
4,Fundraise Up,United States,B2B Software,1250000,Seed,Jan-20
...,...,...,...,...,...,...
2029,Locus Robotics,United States,Robotics,50000000,Series E,Sep-21
2030,Discord,United States,Social Network,500000000,Series H,Sep-21
2031,Qwilt,United States,Telecommunications,70000000,Series E,Sep-21
2032,SmarterTravel,United States,Travel,9500000,Series B,Sep-21
2033,Headout,United States,Travel,12000000,Series B,Sep-21